# Generated by Django 5.1.8 on 2025-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('categoria', models.CharField(choices=[('Sopa', 'Sopa'), ('Doce', 'Doce'), ('Principal', 'Prato Principal'), ('Salada', 'Salada')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
            ],
        ),
    ]
