# Generated by Django 5.1.8 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Sopa', 'Sopa'), ('Doce', 'Doce'), ('Principal', 'Prato Principal'), ('Salada', 'Salada'), ('Lanche', 'Lanche'), ('Bebida', 'Bebida'), ('Molho', 'Molho'), ('Acompanhamento', 'Acompanhamento'), ('Café da Manhã', 'Café da Manhã'), ('Vegano', 'Vegano'), ('Vegetariano', 'Vegetariano'), ('Sobremesa', 'Sobremesa'), ('Petisco', 'Petisco')], max_length=20),
        ),
    ]
